### PR TITLE
Fixed event bubbling when setting scrollLeft for chartScrollContainerHorizontal in scrollTime

### PR DESCRIPTION
**Pull request by litti**
Setting scrollLeft in scrollTime on load leads to an emit of onHorizontalScroll event which leads to layout because getting .scrollLeft value (please read Paul Irish https://gist.github.com/paulirish/5d52fb081b3570c81e3a for detailed information).
Schnappschuss_051719_115546_PM
Schnappschuss_051719_104330_PM

### CODE REVIEW

**Comment by neuronetio** [comment]
you are fckng good :D

**Comment by neuronetio** [comment]
I will check it and if everything is ok i will publish this changes to npm till monday
respect

**Comment by anli-xsigns** [comment]
Thank you :-) Meanwhile I developed the possibility to add resources on the left and more task for one resource in the chart. If resources are not used and only tasks are used the behaviour is like now so existing usage is not broken. Are you interested that I make a push request for these changes?

**Comment by neuronetio** [comment]
Looks good, but I have a little bit different idea to implement this feature.
But thanks!

**Comment by neuronetio** [comment]
I've changed scroll method because it was not smooth enough - I don't know why but it was visible with naked eye.
Probably function call was too expensive here.
You can test if problem with recalculate style still exists - I didn't observe any issues with that.
Recalculate style on my machine takes something like 1ms and below so it is not a problem I think, but when I applied this pull- scrolling was not so smooth - there was visible frames but you must look very carefully.

**Comment by neuronetio** [comment]
problem with recalculate style might be related to vue developer tools also - try to turn it off while measuring performance

**Comment by litti** [comment]
OK, that's an interesting point. Thanks a lot for your hint!

**Pull request merged**
